### ISSUE TITLE
Database Design for the game data

### ISSUE THREAD

**Issue by Phaneendra97** [Phaneendra97/fih-super-set-server#6]
**Purpose:** Teams this issue has been created to get better understanding and gather requirements to design a unified db structure to maintain a standard that helps us write better APIs in the backend. 

**What needs to be done:** Each of the teams please leave a comment on this issue giving a structure of your data it, can be a chart, a db entry snapshot or even a pen and paper table. 

List whatever the data you need to be stored in database, this can be user data related to the game, or the game data itself. Refer to #5, and #3  for better understanding. 

We have come up with a possible structure for now, and we will modify based on your inputs.

![Image](https://github.com/Phaneendra97/fih-super-set-server/assets/22639800/7a205374-f16f-490a-8ff2-f0320122a545)

![Image](https://github.com/Phaneendra97/fih-super-set-server/assets/22639800/cee0cefa-d3cc-4513-b434-5ccd3d8fe298)

Once we have information on the data to be stored from all the games, we will proceed with the database design which will be open for review by each of the teams to make the database design final. 

PS: Since we are using firebase to host the database, there is no structure in db, but for continence and to maintain API standards we are trying to bring little bit of structure. We can always accommodate for changes in the structure of db as development progresses :).

**Comment by kj-grogu** [comment]
In my opinion, instead of having a predefined format for game data for all games, we should let the game owners decide on the format in which they want to keep there game data. so data table should have cols: Game_name, User, game_user_data. here game_user_data column format should not be restrictive, so that all games can put their score and level data in this col as per their needs.
